"""Track 0 -- faithful reproduction of Avellaneda-Stoikov Tables 1-3 & Figures 1-4.

Run:  python track0_paper/run_paper.py
Outputs CSV tables to results/, LaTeX to report/tables.tex, figures to figures/.
"""

import argparse
import json
import os
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Make the project root importable when run as a plain script.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import config
from src import metrics, plotstyle
from src.simulate import simulate, simulate_trace

plotstyle.apply()

RESULTS_DIR = os.path.join(ROOT, "results")
FIG_DIR = os.path.join(ROOT, "figures")
TABLES_TEX = os.path.join(ROOT, "report", "tables.tex")


def run_all(n_sims, seed):
    """Run both strategies for the three gamma settings; return nested results."""
    out = {}
    for gamma in (0.1, 0.01, 0.5):
        out[gamma] = {}
        for strat in ("inventory", "symmetric"):
            # Use the same seed per (gamma) so inventory/symmetric share noise where
            # the kernel draws are aligned; distinct seed per gamma keeps tables independent.
            res = simulate(config.ASParams(gamma=gamma), gamma, strat, n_sims, seed + int(gamma * 1000))
            out[gamma][strat] = res
    return out


def save_tables(results):
    os.makedirs(RESULTS_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(TABLES_TEX), exist_ok=True)
    tex_blocks = [
        "% Auto-generated by track0_paper/run_paper.py -- do not edit by hand.",
    ]
    for gamma in (0.1, 0.01, 0.5):
        rows = [
            metrics.result_row("inventory", results[gamma]["inventory"]),
            metrics.result_row("symmetric", results[gamma]["symmetric"]),
        ]
        metrics.write_csv(os.path.join(RESULTS_DIR, f"table_gamma_{gamma}.csv"), rows)
        tex_blocks.append(metrics.latex_table(gamma, rows, config.PAPER_RESULTS))
        tex_blocks.append("")
    with open(TABLES_TEX, "w", encoding="utf-8") as f:
        f.write("\n".join(tex_blocks))

    # Also dump raw summary stats as JSON for the report / debugging.
    summary = {
        str(g): {
            s: {kk: results[g][s][kk] for kk in
                ("profit_mean", "profit_std", "final_q_mean", "final_q_std")}
            for s in ("inventory", "symmetric")
        }
        for g in (0.1, 0.01, 0.5)
    }
    with open(os.path.join(RESULTS_DIR, "summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)


def fig_quote_path(seed):
    """Figure 1: mid / reservation / bid / ask quotes for one inventory path."""
    tr = simulate_trace(config.ASParams(gamma=0.1), 0.1, seed)
    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.plot(tr["t"], tr["mid"], color=plotstyle.COLOR_MID, lw=1.4, label="中价 (mid-price)")
    ax.plot(tr["t"], tr["ask"], color=plotstyle.COLOR_ASK, lw=0.7, alpha=0.85, label="最优卖价 (ask)")
    ax.plot(tr["t"], tr["bid"], color=plotstyle.COLOR_BID, lw=0.7, alpha=0.85, label="最优买价 (bid)")
    ax.plot(tr["t"], tr["reservation"], color=plotstyle.COLOR_RESERVATION, lw=1.1,
            label="保留价 (reservation)")
    ax.set_xlabel("时间 $t$")
    ax.set_ylabel("价格")
    ax.set_title(r"图1  Avellaneda–Stoikov 做市报价轨迹 ($\gamma=0.1$)")
    ax.legend(loc="best", fontsize=9)
    fig.tight_layout()
    _savefig(fig, "fig1_quote_path")


def fig_pnl_hist(results, gamma, fname):
    """Figures 2-4: P&L histograms, inventory vs symmetric."""
    inv = results[gamma]["inventory"]["profit"]
    sym = results[gamma]["symmetric"]["profit"]
    lo = min(inv.min(), sym.min())
    hi = max(inv.max(), sym.max())
    bins = np.linspace(lo, hi, 60)
    fig, ax = plt.subplots(figsize=(7, 4.2))
    ax.hist(inv, bins=bins, color=plotstyle.COLOR_INVENTORY, alpha=0.85, label="库存策略")
    ax.hist(sym, bins=bins, histtype="step", color=plotstyle.COLOR_MID, lw=1.3, label="对称基准")
    ax.set_xlabel("终端盈亏 (profit)")
    ax.set_ylabel("频数")
    ax.set_title(r"盈亏分布 ($\gamma=%g$)" % gamma)
    ax.legend(loc="best", fontsize=9)
    fig.tight_layout()
    _savefig(fig, fname)


def _savefig(fig, name):
    os.makedirs(FIG_DIR, exist_ok=True)
    fig.savefig(os.path.join(FIG_DIR, name + ".pdf"))
    fig.savefig(os.path.join(FIG_DIR, name + ".png"), dpi=140)
    plt.close(fig)


def print_comparison(results):
    print("\n=== Track 0: reproduction vs. paper (Profit / std / Final q / std) ===")
    for gamma in (0.1, 0.01, 0.5):
        print(f"\ngamma = {gamma}")
        for strat in ("inventory", "symmetric"):
            r = results[gamma][strat]
            p = config.PAPER_RESULTS[gamma][strat]
            print(f"  {strat:10s} ours : "
                  f"{r['profit_mean']:7.2f} {r['profit_std']:7.2f} "
                  f"{r['final_q_mean']:7.3f} {r['final_q_std']:7.2f}")
            print(f"  {strat:10s} paper: "
                  f"{p[0]:7.2f} {p[1]:7.2f} {p[2]:7.3f} {p[3]:7.2f}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sims", type=int, default=config.N_SIMS)
    ap.add_argument("--seed", type=int, default=config.SEED)
    args = ap.parse_args()

    results = run_all(args.sims, args.seed)
    save_tables(results)
    fig_quote_path(args.seed)
    fig_pnl_hist(results, 0.1, "fig2_pnl_gamma_0.1")
    fig_pnl_hist(results, 0.01, "fig3_pnl_gamma_0.01")
    fig_pnl_hist(results, 0.5, "fig4_pnl_gamma_0.5")
    print_comparison(results)
    print(f"\nWrote tables to {RESULTS_DIR} and {TABLES_TEX}")
    print(f"Wrote figures to {FIG_DIR}")


if __name__ == "__main__":
    main()
